name: nampack
description: "Simple reactive library with useful extensions"
version: 0.9.5
homepage:
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  dart_extensions:
    git:
      url: https://github.com/MSOB7YY/dart_extensions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  obx_lints:
    path: ./packages/obx_lints

flutter:
