name: obx_lints
description: provide lint rules for rx implementation
version: 1.1.5

environment:
  sdk: "3.4.0"

dependencies:
  custom_lint:
  analyzer:
  analyzer_plugin:
  custom_lint_builder:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
